
apiVersion: v1
kind: Service
metadata:
  name: nginxsrv
  labels:
    app: nginx
  namespace: dev
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30051
